# -*- coding: utf-8 -*-
"""DAVIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtuanVhc4w9skQxeeOrRdZ8WIj0jxGqW
"""

print("--- Arithmetic Operators ---")
a = 10
b = 3
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a % b = {a % b}")
print(f"a ** b = {a ** b}")
print(f"a // b = {a // b}")

print("\n--- Comparison Operators ---")
x = 10
y = 12
print(f"x == y: {x == y}")
print(f"x != y: {x != y}")
print(f"x > y: {x > y}")
print(f"x < y: {x < y}")
print(f"x >= y: {x >= y}")
print(f"x <= y: {x <= y}")

print("\n--- Logical Operators ---")
p = True
q = False
print(f"p and q: {p and q}")
print(f"p or q: {p or q}")
print(f"not p: {not p}")

print("\n--- Assignment Operators ---")
c = 5
print(f"Initial c: {c}")
c += 3 # c = c + 3
print(f"c += 3: {c}")
c -= 2 # c = c - 2
print(f"c -= 2: {c}")
c *= 4 # c = c * 4
print(f"c *= 4: {c}")
c /= 2 # c = c / 2
print(f"c /= 2: {c}")

print("\n--- Identity Operators ---")
l1 = [1, 2, 3]
l2 = [1, 2, 3]
l3 = l1
print(f"l1 is l2: {l1 is l2}")
print(f"l1 is l3: {l1 is l3}")
print(f"l1 is not l2: {l1 is not l2}")

print("\n--- Membership Operators ---")
my_list = [10, 20, 30, 40]
print(f"20 in my_list: {20 in my_list}")
print(f"50 in my_list: {50 in my_list}")
print(f"30 not in my_list: {30 not in my_list}")

print("\n--- Bitwise Operators ---")
d = 5
e = 3
print(f"d & e (AND): {d & e}")
print(f"d | e (OR): {d | e}")
print(f"d ^ e (XOR): {d ^ e}")
print(f"~d (NOT): {~d}")
print(f"d << 1 (Left Shift): {d << 1}")
print(f"d >> 1 (Right Shift): {d >> 1}")

user_input = input("Please enter something: ")
print(f"You entered: {user_input}")

from IPython.display import display, HTML
variables_data = [
    {'Name': 'a', 'Type': 'int', 'Value': '10'},
    {'Name': 'b', 'Type': 'int', 'Value': '3'},
    {'Name': 'c', 'Type': 'float', 'Value': '12.0'},
    {'Name': 'd', 'Type': 'int', 'Value': '5'},
    {'Name': 'e', 'Type': 'int', 'Value': '3'},
    {'Name': 'l1', 'Type': 'list', 'Value': '[1, 2, 3]'},
    {'Name': 'l2', 'Type': 'list', 'Value': '[1, 2, 3]'},
    {'Name': 'l3', 'Type': 'list', 'Value': '[1, 2, 3]'},
    {'Name': 'my_list', 'Type': 'list', 'Value': '[10, 20, 30, 40]'},
    {'Name': 'p', 'Type': 'bool', 'Value': 'True'},
    {'Name': 'q', 'Type': 'bool', 'Value': 'False'},
    {'Name': 'x', 'Type': 'int', 'Value': '10'},
    {'Name': 'y', 'Type': 'int', 'Value': '12'}
]
html_table = "<table>\n"
html_table += "  <tr><th>Name</th><th>Type</th><th>Value</th></tr>\n"
for var in variables_data:
    html_table += f"  <tr><td>{var['Name']}</td><td>{var['Type']}</td><td>{var['Value']}</td></tr>\n"
html_table += "</table>"

display(HTML(html_table))

# Simple if statement
score = 75
if score >= 60:
    print(f"Your score is {score}. You passed!")

# if-else statement
temperature = 25
if temperature > 30:
    print(f"The temperature is {temperature}°C. It's hot outside!")
else:
    print(f"The temperature is {temperature}°C. It's not too hot.")

marks = 85
if marks >= 90:
    print(f"Your marks are {marks}. Grade: A")
elif marks >= 80:
    print(f"Your marks are {marks}. Grade: B")
elif marks >= 70:
    print(f"Your marks are {marks}. Grade: C")
else:
    print(f"Your marks are {marks}. Grade: F")
num = 10
if num > 0:
    print(f"{num} is a positive number.")
    if num % 2 == 0:
        print(f"{num} is also an even number.")
    else:
        print(f"{num} is also an odd number.")
else:
    print(f"{num} is not a positive number.")

marks = int (input ("Enter your Marks"))
if marks >= 45:
    print(f"Your marks are {marks}. Ressult: Pass")
else:
    print(f"Your marks are {marks}. Result: Fail")



fruits = ["apple", "banana", "cherry"]
print("Fruits:")
for fruit in fruits:
    print(fruit)
word = "Python"
print("\nCharacters in 'Python':")
for char in word:
    print(char)
print("\nNumbers from 0 to 4:")
for i in range(5):
    print(i)
print("\nNumbers from 2 to 9 with step 2:")
for i in range(2, 10, 2):
    print(i)
person = {"name": "Alice", "age": 30, "city": "New York"}
print("\nPerson details (keys):")
for key in person:
    print(key)

print("\nPerson details (values):")
for value in person.values():
    print(value)

print("\nPerson details (items):")
for key, value in person.items():
    print(f"{key}: {value}")

print("\n--- While Loop Examples ---")
count = 0
print("Counting to 3:")
while count < 3:
    print(count)
    count += 1
num = 1
print("\nNumbers (break at 4):")
while True:
    print(num)
    if num == 4:
        break
    num += 1
i = 0
print("\nNumbers (skip 2):")
while i < 5:
    i += 1
    if i == 2:
        continue
    print(i)

print("\nNumbers from 0 to 5:")
for i in range(6):
    print(i)

for i in range(1, 6):
 print(i)

for i in range (5):
  print ("Skyy")

for i in range(1, 6):
    marks = int(input(f"enter marks {i}:"))
    if marks >= 45:
        print(f"Your marks are {marks}. Ressult: Pass")
    else:
        print(f"Your marks are {marks}. Result: Fail")



num = int(input("Enter a number: "))

if num > 0:
    print(f"The number {num} is positive.")
elif num < 0:
    print(f"The number {num} is negative.")
else:
    print(f"The number {num} is zero.")

num = int(input("Enter a number: "))

if num % 2 == 0:
    print(f"The number {num} is even.")
else:
    print(f"The number {num} is odd.")

age = int(input("Enter your age: "))

if age >= 18:
    print(f"You are {age} years old. You are eligible to vote.")
else:
    print(f"You are {age} years old. You are not eligible to vote yet.")

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

if num1 > num2:
    print(f"The greater number is: {num1}")
elif num2 > num1:
    print(f"The greater number is: {num2}")
else:
    print("Both numbers are equal.")

marks = int(input("Enter student's marks: "))

if marks >= 40:
    print(f"The student scored {marks} marks. Result: Pass")
else:
    print(f"The student scored {marks} marks. Result: Fail")



num = int(input("Enter a number: "))

if num % 10 == 0:
    print(f"The number {num} is divisible by both 5 and 10.")
else:
    print(f"The number {num} is not divisible by both 5 and 10.")

char = input("Enter a character: ")
char_lower = char.lower()

vowels = 'aeiou'

if len(char) == 1 and char_lower.isalpha():
    if char_lower in vowels:
        print(f"The character '{char}' is a vowel.")
    else:
        print(f"The character '{char}' is a consonant.")
elif len(char) != 1:
    print("Please enter a single character.")
else:
    print("Invalid input. Please enter an alphabet character.")

units = float(input("Enter the number of units consumed: "))

bill = 0

if units <= 50:
    bill = units * 0.50
elif units <= 150:
    bill = (unit * 0.25)
elif units <= 250:
    bill = (unit * 0.50)
else:
    bill = (unit * 0.75)

print(f"Electricity bill for {units} units is: ${bill:.2f}")

year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"The year {year} is a leap year.")
else:
    print(f"The year {year} is not a leap year.")

salary = float(input("Enter the employee's salary: "))

bonus_percentage = 0

if salary >= 50000:
    bonus_percentage = 0.15
elif salary >= 30000:
    bonus_percentage = 0.10
else:
    bonus_percentage = 0.05

bonus_amount = salary * bonus_percentage
total_compensation = salary + bonus_amount

print(f"Employee Salary: ${salary:.2f}")
print(f"Bonus Percentage: {bonus_percentage * 100:.0f}%")
print(f"Bonus Amount: ${bonus_amount:.2f}")
print(f"Total Compensation: ${total_compensation:.2f}")

for i in range(1, 11):
    print(i)

print("Even numbers between 1 and 50:")
for num in range(2, 51, 2):
    print(num)

sum_natural_numbers = 0
for i in range(1, 11):
    sum_natural_numbers += i
print(f"The sum of the first 10 natural numbers is: {sum_natural_numbers}")

num = int(input("Enter a number to see its multiplication table: "))

print(f"Multiplication Table for {num}:")
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

num_str = input("Enter a number: ")
if num_str.isdigit():
    number = int(num_str)
    num_digits = len(str(abs(number)))
    print(f"The number {number} has {num_digits} digits.")
else:
    print("Invalid input. Please enter an integer.")

for i in range(1, 6):
    marks = int(input(f"Enter marks for student {i}: "))
    if marks >= 45:
        print(f"Student {i}: Your marks are {marks}. Result: Pass")
    else:
        print(f"Student {i}: Your marks are {marks}. Result: Fail")

for i in range(1, 101):
    if i % 2 == 0:
        print(f"{i}: Even")
    else:
        print(f"{i}: Odd")

count = 0
for i in range(1, 51):
    if i % 3 == 0:
        count += 1
print(f"There are {count} numbers between 1 and 50 that are divisible by 3.")

8total_marks = 0
num_students = 5

for i in range(1, num_students + 1):
    marks = int(input(f"Enter marks for student {i}: "))
    total_marks += marks

average_marks = total_marks / num_students
print(f"The average marks for {num_students} students is: {average_marks:.2f}")

positive_count = 0
negative_count = 0

print("Please enter 5 numbers:")

for i in range(5):
    try:
        num = float(input(f"Enter number {i+1}: "))
        if num > 0:
            positive_count += 1
        elif num < 0:
            negative_count += 1
    except ValueError:
        print("Invalid input. Please enter a valid number.")

print(f"\nNumber of positive numbers: {positive_count}")
print(f"Number of negative numbers: {negative_count}")